volumes:
  data:

  services:
    mongodb:
      image: mongo:latest
      environment:
        - MONGO_INITDB_ROOT_USERNAME=andreiacarvalho
        - MONGO_INITDB_ROOT_PASSWORD=ChatMongoDB123
      ports:
        - 27017:27017
      volumes:
        - data:/data/db
    myapp:
      image: react-fb_login_react-app
